export const PRODUCTS_GET = "PRODUCTS_GET";
export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const SET_PRODUCTS_OPTIONS = "SET_PRODUCTS_OPTIONS";
export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_GET = "PRODUCT_GET";
